name: Generate Proto

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Make
      run: sudo apt-get install make

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Install Protobuf Compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-go and protoc-gen-go-grpc
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Run Makefile
      run: make -C week-3

    - name: Commit and push generated files
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add week-3/gen
        git commit -m "Generate protobuf files" || echo "No changes to commit"
        git push origin master || echo "No changes to push"
