name: Generate Proto

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.GH_TOKEN }}

    - name: Set up Make
      run: sudo apt-get install make

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Install Protobuf Compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-go and protoc-gen-go-grpc
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Run Makefile
      run: make -C week-3

    - name: Commit and push generated files
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Generate protobuf files" || echo "No changes to commit"
        git push https://x-access-token:${GH_TOKEN}@github.com/wickyou23/learning-golang-proto.git master || echo "No changes to push"

    - name: Tag the new version
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        VERSION=$(date +'%Y%m%d%H%M%S')
        git tag -a "v$VERSION" -m "Generated protobuf files version $VERSION"
        git push https://x-access-token:${GH_TOKEN}@github.com/wickyou23/learning-golang-proto.git --tags
